// Draws every Comp HQ icon from the one design file (SPEC B11.2, PLAN P5-05).
//
//   npm run icons
//
// tools/icons/comphq.design.svg is the only place the mark is designed. This
// script (1) embeds the vendored Big Shoulders Display font into it, writing
// web/static/theme/icons/comphq.svg, so the SVG draws the same on a computer
// that has no such font; and (2) has the browser we already test with draw that
// SVG at each size the browsers and Windows ask for, writing the PNGs and the
// multi-size .ico beside it. Nothing is exported by hand, so no size can drift
// from another. It is a developer tool: the app never runs it, and the results
// are committed.
import { chromium } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const iconsDir = path.join(root, 'web', 'static', 'theme', 'icons');
const fontFile = path.join(root, 'web', 'static', 'theme', 'fonts', 'big-shoulders-display-variable.woff2');
const designFile = path.join(root, 'tools', 'icons', 'comphq.design.svg');

// The sizes browsers, Windows and installed apps ask for (gate 5.21). At 16 and
// 32 the two-line wordmark is unreadable, so those two draw HQ alone.
export const PNG_SIZES = [16, 32, 48, 64, 128, 192, 256, 512];
export const ICO_SIZES = [16, 32, 48, 64, 128, 256];
const HQ_ONLY_BELOW = 48;

/** The design file with the font embedded, and its design comment left out. */
function buildSelfContainedSvg() {
  const font = fs.readFileSync(fontFile).toString('base64');
  const design = fs.readFileSync(designFile, 'utf8').replace(/\r\n/g, '\n');
  const style =
    '<style>@font-face{font-family:"Big Shoulders Display";' +
    `src:url(data:font/woff2;base64,${font}) format("woff2");font-weight:100 900;font-style:normal}</style>`;
  return design
    .replace(/<!--[\s\S]*?-->\n/, '<!-- Generated by `npm run icons` from tools/icons/comphq.design.svg. Edit that file, not this one. -->\n')
    .replace('</title>\n', `</title>\n${style}\n`);
}

/** PNG-in-ICO, the form Windows has read since Vista: a directory, then each PNG whole. */
function buildIco(images) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(images.length, 4);
  const entries = [];
  let offset = 6 + 16 * images.length;
  for (const { size, png } of images) {
    const e = Buffer.alloc(16);
    e.writeUInt8(size >= 256 ? 0 : size, 0); // 0 means 256
    e.writeUInt8(size >= 256 ? 0 : size, 1);
    e.writeUInt8(0, 2); // palette
    e.writeUInt8(0, 3);
    e.writeUInt16LE(1, 4); // colour planes
    e.writeUInt16LE(32, 6); // bits per pixel
    e.writeUInt32LE(png.length, 8);
    e.writeUInt32LE(offset, 12);
    entries.push(e);
    offset += png.length;
  }
  return Buffer.concat([header, ...entries, ...images.map((i) => i.png)]);
}

async function main() {
  const svg = buildSelfContainedSvg();
  fs.mkdirSync(iconsDir, { recursive: true });
  fs.writeFileSync(path.join(iconsDir, 'comphq.svg'), svg);

  const browser = await chromium.launch();
  const context = await browser.newContext({ deviceScaleFactor: 1 });
  const page = await context.newPage();

  async function draw(size, { hqOnly, square }) {
    await page.setViewportSize({ width: size, height: size });
    await page.setContent(`<!doctype html><html><body style="margin:0;background:transparent">${svg}</body></html>`);
    await page.evaluate(
      async ({ size, hqOnly, square }) => {
        await document.fonts.load('900 100px "Big Shoulders Display"');
        await document.fonts.load('800 100px "Big Shoulders Display"');
        const el = document.querySelector('svg');
        el.setAttribute('width', size);
        el.setAttribute('height', size);
        el.style.display = 'block';
        el.querySelector('#stacked').setAttribute('display', hqOnly ? 'none' : 'inline');
        el.querySelector('#hq-only').setAttribute('display', hqOnly ? 'inline' : 'none');
        if (square) el.querySelector('#field').setAttribute('rx', '0');
        await document.fonts.ready;
        if (!document.fonts.check('900 100px "Big Shoulders Display"')) throw new Error('the embedded font did not load');
      },
      { size, hqOnly, square },
    );
    return page.screenshot({ omitBackground: true, type: 'png', clip: { x: 0, y: 0, width: size, height: size } });
  }

  const byPngSize = new Map();
  for (const size of PNG_SIZES) {
    const png = await draw(size, { hqOnly: size < HQ_ONLY_BELOW, square: false });
    byPngSize.set(size, png);
    fs.writeFileSync(path.join(iconsDir, `icon-${size}.png`), png);
  }
  // The maskable icon fills the whole square; Windows and Android crop it to
  // whatever shape they use, and the letters stay inside the safe circle.
  fs.writeFileSync(path.join(iconsDir, 'icon-maskable-512.png'), await draw(512, { hqOnly: false, square: true }));

  const ico = buildIco(ICO_SIZES.map((size) => ({ size, png: byPngSize.get(size) })));
  fs.writeFileSync(path.join(iconsDir, 'comphq.ico'), ico);

  await browser.close();
  console.log(`wrote comphq.svg, comphq.ico, ${PNG_SIZES.length} PNGs and the maskable icon to ${path.relative(root, iconsDir)}`);
}

// Only when run directly, so the sizes above can be imported by a test.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
