// Rebuilds the one-time editor bundle (dev only). The output is committed;
// CI proves it's reproducible by re-running this and diffing (P1-09).
import * as esbuild from 'esbuild'
import { createHash } from 'node:crypto'
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..', '..')
const outDir = path.join(root, 'web', 'static', 'vendor', 'editor')
const outFile = path.join(outDir, 'editor-3.31.3.js')

await esbuild.build({
  entryPoints: [path.join(here, 'entry.js')],
  outfile: outFile,
  bundle: true,
  minify: true,
  sourcemap: false,
  format: 'iife',
  target: ['chrome120'],
  legalComments: 'none',
})
console.log('wrote web/static/vendor/editor/editor-3.31.3.js')

writeLicenses()
console.log('wrote web/static/vendor/editor/LICENSES.txt')

writeVendorEntry()
console.log('updated web/static/vendor/VENDOR.md')

// Every MIT package bundled into editor-3.31.3.js, grouped by the
// copyright holder whose LICENSE file we found, so nothing is missed as
// dependencies change.
function bundledPackageDirs() {
  const nodeModules = path.join(root, 'node_modules')
  const dirs = []
  for (const name of fs.readdirSync(nodeModules)) {
    if (name.startsWith('prosemirror-') || name === 'linkifyjs') {
      dirs.push(path.join(nodeModules, name))
    }
  }
  for (const name of fs.readdirSync(path.join(nodeModules, '@tiptap'))) {
    dirs.push(path.join(nodeModules, '@tiptap', name))
  }
  return dirs.sort()
}

function readLicenseFile(dir) {
  for (const candidate of ['LICENSE', 'LICENSE.md', 'LICENSE.txt']) {
    const p = path.join(dir, candidate)
    if (fs.existsSync(p)) return fs.readFileSync(p, 'utf8').trim()
  }
  return null
}

function writeLicenses() {
  const groups = new Map() // license text -> package names
  for (const dir of bundledPackageDirs()) {
    const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'))
    const text = readLicenseFile(dir)
    if (!text) throw new Error(`no LICENSE file found for ${pkg.name}`)
    const label = `${pkg.name}@${pkg.version}`
    if (!groups.has(text)) groups.set(text, [])
    groups.get(text).push(label)
  }

  const sections = [...groups.entries()]
    .map(([text, names]) => `${names.sort().join(', ')}\n${'-'.repeat(40)}\n${text}`)
    .sort()

  const header =
    'Licences for the third-party code bundled into editor-3.31.3.js\n' +
    '(TipTap, ProseMirror and linkifyjs — all MIT). Regenerated by\n' +
    '`npm run vendor:editor`; do not edit by hand.\n\n'

  fs.writeFileSync(path.join(outDir, 'LICENSES.txt'), header + sections.join('\n\n') + '\n')
}

function writeVendorEntry() {
  const bytes = fs.readFileSync(outFile)
  const sha256 = createHash('sha256').update(bytes).digest('hex')
  const vendorMdPath = path.join(root, 'web', 'static', 'vendor', 'VENDOR.md')

  const row = `| editor-3.31.3.js | TipTap 3.31.3 (+ ProseMirror, linkifyjs) | MIT | npm: @tiptap/* | \`editor/editor-3.31.3.js\` | ${sha256} |`

  const header =
    '# Vendored third-party files\n\n' +
    'Recomputed by the policy tests (`tools/policy`), which fail if a checksum here stops matching the file.\n\n' +
    '| Name | Version | Licence | Source | Path | SHA-256 |\n' +
    '|---|---|---|---|---|---|\n'

  let rows = [row]
  if (fs.existsSync(vendorMdPath)) {
    const existing = fs.readFileSync(vendorMdPath, 'utf8')
    const lines = existing.split('\n')
    const dataLines = lines.filter(
      (l) => l.startsWith('|') && !l.startsWith('| Name') && !l.startsWith('|---'),
    )
    const otherRows = dataLines.filter((l) => !l.includes('editor-3.31.3.js'))
    rows = [...otherRows, row]
  }
  // Sorted by name (not appended at the end): another vendor script
  // touching this same shared file, run in either order, must produce
  // byte-identical output, or CI's "bundle is reproducible" check
  // (which only re-runs *this* script and diffs) sees a false failure
  // whenever the file was last written by a different script.
  rows.sort()
  const content = header + rows.join('\n') + '\n'

  fs.writeFileSync(vendorMdPath, content)
}
